name: flutter_hide_seek_cat
description: A hide seek cat Application for young boys and girls.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  # sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 屏幕适配
  flutter_screenutil: ^4.0.3+2
  # rive(flare)动画
  rive: ^0.7.0
  # toast
  fluttertoast: ^7.1.6
  # 网络请求
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  # 本地存储
  shared_preferences: ^2.0.3
  # 状态管理
  provider: ^5.0.0
  # 骨架屏
  pk_skeleton: ^0.0.2
  # webview
  webview_flutter: ^2.0.2
  # 分享
  share: ^2.0.1
  # 设备信息
  device_info: ^2.0.0
  # 包信息
  package_info: ^2.0.0
  # 路径
  path_provider: ^2.0.1
  # 权限处理
  permission_handler: ^6.1.1
  # 安装apk
  install_plugin: ^2.0.1
  # 错误上报
  sentry_flutter: ^4.0.6
  # allows us to easily use any of the 977 fonts from fonts.google.com
  google_fonts: ^2.0.0
  # 国际化和本地化功能，包括消息翻译，复数形式和性别，日期/数字格式和解析以及双向文本
  intl: ^0.17.0
  # realtime chat
  socket_io_client: 2.0.0-beta.3-nullsafety.0
  # 跑马灯
  marquee: ^2.0.0
  # 相册选择
  image_picker: ^0.7.4
  # 保存图片到相册
  image_gallery_saver: ^1.6.9
  # 瀑布流布局
  flutter_staggered_grid_view: ^0.3.4
  # 视频播放
  video_player: ^2.1.1
  # 生成二维码
  qr_flutter: ^4.0.0
  # 扫描二维码
  qr_code_scanner: ^0.4.0

  # 音频播放
  # audioplayers: ^0.18.3

  
  # 序列化JSON
  json_annotation: 3.1.1

dependency_overrides:
  graphs: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter
  build_runner: 1.11.5
  json_serializable: 3.5.1
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cat.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/rives/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Yinlei
      fonts:
        - asset: assets/fonts/hide-seek.ttf
          weight: 400
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf